import type { EffectCycle } from "../../src/effects/types";

export function makeEffectCycle(overrides: Partial<EffectCycle> = {}): EffectCycle {
  return {
    cycleId: "cycle-1",
    recId: "rec-test-1",
    cycleNo: 1,
    contractVersion: "esf-effect-1",
    queryDefinitionVersion: "esf-1",
    versionStatus: "SUPPORTED",
    detectorId: "D2",
    metricId: "avg_context_per_turn",
    methodVersion: "esf-1",
    state: "OPEN_MEASURING",
    createdAt: "2026-09-01T00:00:00.000Z",
    trackingRequestedAt: "2026-09-01T00:00:00.000Z",
    appliedAt: "2026-09-01T00:00:00.000Z",
    applicationSource: "USER_ATTESTED",
    actionRevision: null,
    scope: { workspaceId: null },
    cohort: {},
    targetDefinition: {
      metricId: "avg_context_per_turn",
      methodVersion: "esf-1",
      unit: "tokens",
      sampleUnit: "turn",
      aggregation: "mean",
      deltaSemantics: "RELATIVE_PERCENT",
      improvementThreshold: 5,
      worseningThreshold: 5,
      eligibleDefinition: "eligible turns",
      excludedDefinition: "excluded turns",
      denominatorDefinition: "turn count",
      boundaryRule: "half-open",
      minimumSessions: 3,
    },
    guardrailDefinitions: [{ guardrailId: "latency", methodVersion: "esf-1", unit: "ms" }],
    baselineFrom: "2026-08-18T00:00:00.000Z",
    baselineTo: "2026-09-01T00:00:00.000Z",
    observationFrom: "2026-09-01T00:00:00.000Z",
    scheduledObservationTo: "2026-09-30T00:00:00.000Z",
    observationTo: null,
    baselineEvidence: { value: 100, denominator: null, exposureN: 3, sessionN: 3, excluded: {} },
    provisionalEvidence: null,
    finalEvidence: null,
    targetDirection: null,
    comparisonStatus: null,
    comparisonReasons: [],
    terminalAt: null,
    terminalReason: null,
    attributionClosedAt: null,
    attributionCloseReason: null,
    finalizerRevision: null,
    concurrentChange: null,
    rollbackStatus: null,
    rollbackAt: null,
    rollbackAttestationSource: null,
    ...overrides,
  };
}
